/*
 * IMPORTANT!
 * This file has been automatically generated.
 * In order to update its content based on rules'
 * definitions, execute "npm run update"
 */
module.exports = {
  "ember/avoid-leaking-state-in-ember-objects": "error",
  "ember/avoid-using-needs-in-controllers": "error",
  "ember/closure-actions": "error",
  "ember/jquery-ember-run": "error",
  "ember/new-module-imports": "error",
  "ember/no-arrow-function-computed-properties": "error",
  "ember/no-attrs-in-components": "error",
  "ember/no-attrs-snapshot": "error",
  "ember/no-capital-letters-in-routes": "error",
  "ember/no-deeply-nested-dependent-keys-with-each": "error",
  "ember/no-duplicate-dependent-keys": "error",
  "ember/no-ember-super-in-es-classes": "error",
  "ember/no-ember-testing-in-module-scope": "error",
  "ember/no-function-prototype-extensions": "error",
  "ember/no-get-with-default": "error",
  "ember/no-get": "error",
  "ember/no-global-jquery": "error",
  "ember/no-incorrect-calls-with-inline-anonymous-functions": "error",
  "ember/no-incorrect-computed-macros": "error",
  "ember/no-invalid-debug-function-arguments": "error",
  "ember/no-invalid-dependent-keys": "error",
  "ember/no-jquery": "error",
  "ember/no-legacy-test-waiters": "error",
  "ember/no-mixins": "error",
  "ember/no-new-mixins": "error",
  "ember/no-observers": "error",
  "ember/no-old-shims": "error",
  "ember/no-on-calls-in-components": "error",
  "ember/no-pause-test": "error",
  "ember/no-private-routing-service": "error",
  "ember/no-restricted-resolver-tests": "error",
  "ember/no-side-effects": "error",
  "ember/no-test-and-then": "error",
  "ember/no-test-import-export": "error",
  "ember/no-test-module-for": "error",
  "ember/no-unnecessary-route-path-option": "error",
  "ember/no-volatile-computed-properties": "error",
  "ember/require-computed-macros": "error",
  "ember/require-computed-property-dependencies": "error",
  "ember/require-return-from-computed": "error",
  "ember/require-super-in-init": "error",
  "ember/routes-segments-snake-case": "error",
  "ember/use-brace-expansion": "error",
  "ember/use-ember-data-rfc-395-imports": "error"
}